is_train: False
image_size: 33
label_size: 21
batch_size: 64
upscale: 2
test_index: 0
scale: 3
stride: 14
dataset:
  train_path: "Train"
  test_path: "Test"
train:
  use_cuda: True
  lr: 1e-6
  epoches: 100
  
